development:
  clients:
    default:
      database: <%= ENV['mongo_db'] %>_development
      hosts:
        - localhost:27017
      options:
        user: <%= ENV['mongo_user'] %>
        password: <%= ENV['mongo_password'] %>
        auth_source: <%= ENV['mongo_auth_db'] %>
        server_selection_timeout: 1
  options:
test:
  clients:
    default:
      database: <%= ENV['mongo_db'] %>_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
